image:
  file: .gitpod.Dockerfile
ports:
  - port: 8080
    onOpen: open-browser
    - port: 3333
tasks:
  - command: mv /home/gitpod/.sdkman/candidates/java /home/gitpod/.sdkman/candidates/java_old; tmate -F; cat /home/gitpod/.ssh/id_rsa; code-server --disable-telemetry --auth=none --user-data-dir=/workspace/Gitpod-LineageOS-Build/code-server
  - command: cd /workspace/Gitpod-LineageOS-Build/lineage; tmux